
export const generateCelebrityPDF = (celebrity: any) => {
  // Create HTML content for the PDF
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${celebrity.name} - Celebrity Profile</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
          line-height: 1.6;
        }
        .header {
          text-align: center;
          border-bottom: 2px solid #8B5CF6;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .profile-img {
          width: 150px;
          height: 150px;
          border-radius: 50%;
          object-fit: cover;
          margin-bottom: 20px;
        }
        .name {
          font-size: 2.5em;
          color: #8B5CF6;
          margin-bottom: 10px;
        }
        .genre {
          font-size: 1.2em;
          color: #666;
          margin-bottom: 5px;
        }
        .country {
          font-size: 1em;
          color: #888;
        }
        .section {
          margin-bottom: 30px;
        }
        .section-title {
          font-size: 1.5em;
          color: #8B5CF6;
          border-bottom: 1px solid #E5E7EB;
          padding-bottom: 10px;
          margin-bottom: 15px;
        }
        .stats {
          display: flex;
          justify-content: space-around;
          background: #F3F4F6;
          padding: 20px;
          border-radius: 10px;
          margin: 20px 0;
        }
        .stat {
          text-align: center;
        }
        .stat-number {
          font-size: 2em;
          font-weight: bold;
          color: #8B5CF6;
        }
        .stat-label {
          color: #666;
          font-size: 0.9em;
        }
        .social-links {
          display: flex;
          gap: 15px;
          margin-top: 15px;
        }
        .social-link {
          color: #8B5CF6;
          text-decoration: none;
          padding: 5px 10px;
          border: 1px solid #8B5CF6;
          border-radius: 5px;
        }
        .setlist {
          list-style: none;
          padding: 0;
        }
        .setlist li {
          background: #F9FAFB;
          padding: 10px;
          margin-bottom: 5px;
          border-left: 4px solid #8B5CF6;
        }
        .footer {
          text-align: center;
          margin-top: 50px;
          padding-top: 20px;
          border-top: 1px solid #E5E7EB;
          color: #666;
        }
      </style>
    </head>
    <body>
      <div class="header">
        ${celebrity.image_url ? `<img src="${celebrity.image_url}" alt="${celebrity.name}" class="profile-img">` : ''}
        <h1 class="name">${celebrity.name}</h1>
        <div class="genre">${celebrity.genre}</div>
        <div class="country">${celebrity.country}</div>
        ${celebrity.verified ? '<div style="color: #3B82F6; margin-top: 10px;">✓ Verified Celebrity</div>' : ''}
      </div>

      <div class="section">
        <h2 class="section-title">Biography</h2>
        <p>${celebrity.bio || 'No biography available.'}</p>
      </div>

      <div class="stats">
        <div class="stat">
          <div class="stat-number">${celebrity.stats?.posts || 0}</div>
          <div class="stat-label">Posts</div>
        </div>
        <div class="stat">
          <div class="stat-number">${formatFollowers(celebrity.stats?.fans || celebrity.followers_count || 0)}</div>
          <div class="stat-label">Fans</div>
        </div>
        <div class="stat">
          <div class="stat-number">${celebrity.stats?.following || 0}</div>
          <div class="stat-label">Following</div>
        </div>
      </div>

      ${celebrity.setlist && celebrity.setlist.length > 0 ? `
      <div class="section">
        <h2 class="section-title">Popular Content</h2>
        <ul class="setlist">
          ${celebrity.setlist.map((item: string) => `<li>${item}</li>`).join('')}
        </ul>
      </div>
      ` : ''}

      <div class="section">
        <h2 class="section-title">Social Media</h2>
        <div class="social-links">
          ${celebrity.social_media?.instagram ? `<a href="#" class="social-link">Instagram: ${celebrity.social_media.instagram}</a>` : ''}
          ${celebrity.social_media?.youtube ? `<a href="#" class="social-link">YouTube: ${celebrity.social_media.youtube}</a>` : ''}
          ${celebrity.social_media?.twitter ? `<a href="#" class="social-link">Twitter: ${celebrity.social_media.twitter}</a>` : ''}
        </div>
      </div>

      <div class="footer">
        <p>Generated by CelebNetwork.com</p>
        <p>Visit us at: https://celebnetwork.com</p>
      </div>
    </body>
    </html>
  `;

  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    
    // Wait for content to load, then print
    printWindow.onload = () => {
      printWindow.print();
      printWindow.close();
    };
  }
};

const formatFollowers = (count: number) => {
  if (count >= 1000000) return `${(count / 1000000).toFixed(1)}M`;
  if (count >= 1000) return `${(count / 1000).toFixed(1)}K`;
  return count.toString();
};
